### PR TITLE
host: sm: ignore security request, add test

### PR DESCRIPTION
**Pull request by piotrnarajowski**
- Ignore security request that was recived after pairing has already started - fixes SM/CEN/PIS/BV-03-C
- Add and fix SM unit tests

### CODE REVIEW

**Comment by piotrnarajowski** [comment]
#AutoPTS run mynewt SM

**Comment by codecoup-tester** [comment]
Scheduled PR https://github.com/apache/mynewt-nimble/pull/1826#issuecomment-2263272206, board: nrf52, estimated start time: 16:52:19, test case count: 62, estimated duration: 0:30:06<details><summary>Test cases to be run</summary>SM/CEN/PROT/BV-01-C<br>SM/CEN/JW/BV-05-C<br>SM/CEN/JW/BI-04-C<br>SM/CEN/JW/BI-01-C<br>SM/CEN/PKE/BV-01-C<br>SM/CEN/PKE/BV-04-C<br>SM/CEN/PKE/BI-01-C<br>SM/CEN/PKE/BI-02-C<br>SM/CEN/OOB/BV-01-C<br>SM/CEN/OOB/BV-03-C<br>SM/CEN/OOB/BV-09-C<br>SM/CEN/OOB/BI-01-C<br>SM/CEN/EKS/BV-01-C<br>SM/CEN/EKS/BI-01-C<br>SM/CEN/KDU/BV-05-C<br>SM/CEN/KDU/BV-06-C<br>SM/CEN/KDU/BV-10-C<br>SM/CEN/KDU/BI-01-C<br>SM/CEN/PIS/BV-02-C<br>SM/CEN/PIS/BV-03-C<br>SM/CEN/SCJW/BV-01-C<br>SM/CEN/SCJW/BV-04-C<br>SM/CEN/SCJW/BI-01-C<br>SM/CEN/SCPK/BV-01-C<br>SM/CEN/SCPK/BV-04-C<br>SM/CEN/SCPK/BI-01-C<br>SM/CEN/SCPK/BI-02-C<br>SM/CEN/SCOB/BV-01-C<br>SM/CEN/SCOB/BV-04-C<br>SM/CEN/SCOB/BI-01-C<br>SM/CEN/SCOB/BI-04-C<br>SM/PER/PROT/BV-02-C<br>SM/PER/JW/BV-02-C<br>SM/PER/JW/BI-03-C<br>SM/PER/JW/BI-02-C<br>SM/PER/PKE/BV-02-C<br>SM/PER/PKE/BV-05-C<br>SM/PER/PKE/BI-03-C<br>SM/PER/OOB/BV-02-C<br>SM/PER/OOB/BV-04-C<br>SM/PER/OOB/BV-10-C<br>SM/PER/OOB/BI-02-C<br>SM/PER/EKS/BV-02-C<br>SM/PER/EKS/BI-02-C<br>SM/PER/KDU/BV-01-C<br>SM/PER/KDU/BV-02-C<br>SM/PER/KDU/BV-07-C<br>SM/PER/KDU/BV-08-C<br>SM/PER/KDU/BI-01-C<br>SM/PER/PIS/BV-01-C<br>SM/PER/PIS/BV-02-C<br>SM/PER/SCJW/BV-02-C<br>SM/PER/SCJW/BV-03-C<br>SM/PER/SCJW/BI-02-C<br>SM/PER/SCPK/BV-02-C<br>SM/PER/SCPK/BV-03-C<br>SM/PER/SCPK/BI-03-C<br>SM/PER/SCPK/BI-04-C<br>SM/PER/SCOB/BV-02-C<br>SM/PER/SCOB/BV-03-C<br>SM/PER/SCOB/BI-02-C<br>SM/PER/SCOB/BI-03-C</details>

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
No failed test found.
<details><summary>Successful tests</summary>SM      SM/CEN/EKS/BI-01-C              PASS<br>SM      SM/CEN/EKS/BV-01-C              PASS<br>SM      SM/CEN/JW/BI-01-C               PASS<br>SM      SM/CEN/JW/BI-04-C               PASS<br>SM      SM/CEN/JW/BV-05-C               PASS<br>SM      SM/CEN/KDU/BI-01-C              PASS<br>SM      SM/CEN/KDU/BV-05-C              PASS<br>SM      SM/CEN/KDU/BV-06-C              PASS<br>SM      SM/CEN/KDU/BV-10-C              PASS<br>SM      SM/CEN/OOB/BI-01-C              PASS<br>SM      SM/CEN/OOB/BV-01-C              PASS<br>SM      SM/CEN/OOB/BV-03-C              PASS<br>SM      SM/CEN/OOB/BV-09-C              PASS<br>SM      SM/CEN/PIS/BV-02-C              PASS<br>SM      SM/CEN/PIS/BV-03-C              PASS<br>SM      SM/CEN/PKE/BI-01-C              PASS<br>SM      SM/CEN/PKE/BI-02-C              PASS<br>SM      SM/CEN/PKE/BV-01-C              PASS<br>SM      SM/CEN/PKE/BV-04-C              PASS<br>SM      SM/CEN/PROT/BV-01-C             PASS<br>SM      SM/CEN/SCJW/BI-01-C             PASS<br>SM      SM/CEN/SCJW/BV-01-C             PASS<br>SM      SM/CEN/SCJW/BV-04-C             PASS<br>SM      SM/CEN/SCOB/BI-01-C             PASS<br>SM      SM/CEN/SCOB/BI-04-C             PASS<br>SM      SM/CEN/SCOB/BV-01-C             PASS<br>SM      SM/CEN/SCOB/BV-04-C             PASS<br>SM      SM/CEN/SCPK/BI-01-C             PASS<br>SM      SM/CEN/SCPK/BI-02-C             PASS<br>SM      SM/CEN/SCPK/BV-01-C             PASS<br>SM      SM/CEN/SCPK/BV-04-C             PASS<br>SM      SM/PER/EKS/BI-02-C              PASS<br>SM      SM/PER/EKS/BV-02-C              PASS<br>SM      SM/PER/JW/BI-02-C               PASS<br>SM      SM/PER/JW/BI-03-C               PASS<br>SM      SM/PER/JW/BV-02-C               PASS<br>SM      SM/PER/KDU/BI-01-C              PASS<br>SM      SM/PER/KDU/BV-01-C              PASS<br>SM      SM/PER/KDU/BV-02-C              PASS<br>SM      SM/PER/KDU/BV-07-C              PASS<br>SM      SM/PER/KDU/BV-08-C              PASS<br>SM      SM/PER/OOB/BI-02-C              PASS<br>SM      SM/PER/OOB/BV-02-C              PASS<br>SM      SM/PER/OOB/BV-04-C              PASS<br>SM      SM/PER/OOB/BV-10-C              PASS<br>SM      SM/PER/PIS/BV-01-C              PASS<br>SM      SM/PER/PIS/BV-02-C              PASS<br>SM      SM/PER/PKE/BI-03-C              PASS<br>SM      SM/PER/PKE/BV-02-C              PASS<br>SM      SM/PER/PKE/BV-05-C              PASS<br>SM      SM/PER/PROT/BV-02-C             PASS<br>SM      SM/PER/SCJW/BI-02-C             PASS<br>SM      SM/PER/SCJW/BV-02-C             PASS<br>SM      SM/PER/SCJW/BV-03-C             PASS<br>SM      SM/PER/SCOB/BI-02-C             PASS<br>SM      SM/PER/SCOB/BI-03-C             PASS<br>SM      SM/PER/SCOB/BV-02-C             PASS<br>SM      SM/PER/SCOB/BV-03-C             PASS<br>SM      SM/PER/SCPK/BI-03-C             PASS<br>SM      SM/PER/SCPK/BI-04-C             PASS<br>SM      SM/PER/SCPK/BV-02-C             PASS<br>SM      SM/PER/SCPK/BV-03-C             PASS</details>

**Comment by codecoup-tester** [comment]
Scheduled PR https://github.com/apache/mynewt-nimble/pull/1826#issuecomment-2263378919, board: nrf52, estimated start time: 17:39:59, test case count: 142, estimated duration: 1:26:58<details><summary>Test cases to be run</summary>GAP/BROB/BCST/BV-01-C<br>GAP/BROB/BCST/BV-02-C<br>GAP/BROB/BCST/BV-03-C<br>GAP/BROB/BCST/BV-04-C<br>GAP/BROB/OBSV/BV-01-C<br>GAP/BROB/OBSV/BV-02-C<br>GAP/BROB/OBSV/BV-05-C<br>GAP/BROB/OBSV/BV-06-C<br>GAP/DISC/NONM/BV-01-C<br>GAP/DISC/NONM/BV-02-C<br>GAP/DISC/LIMM/BV-03-C<br>GAP/DISC/LIMM/BV-04-C<br>GAP/DISC/GENM/BV-03-C<br>GAP/DISC/GENM/BV-04-C<br>GAP/DISC/LIMP/BV-01-C<br>GAP/DISC/LIMP/BV-02-C<br>GAP/DISC/LIMP/BV-03-C<br>GAP/DISC/LIMP/BV-04-C<br>GAP/DISC/LIMP/BV-05-C<br>GAP/DISC/GENP/BV-01-C<br>GAP/DISC/GENP/BV-02-C<br>GAP/DISC/GENP/BV-03-C<br>GAP/DISC/GENP/BV-04-C<br>GAP/DISC/GENP/BV-05-C<br>GAP/DISC/RPA/BV-01-C<br>GAP/IDLE/NAMP/BV-01-C<br>GAP/IDLE/NAMP/BV-02-C<br>GAP/CONN/NCON/BV-01-C<br>GAP/CONN/NCON/BV-02-C<br>GAP/CONN/NCON/BV-03-C<br>GAP/CONN/DCON/BV-01-C<br>GAP/CONN/UCON/BV-01-C<br>GAP/CONN/UCON/BV-02-C<br>GAP/CONN/UCON/BV-03-C<br>GAP/CONN/UCON/BV-06-C<br>GAP/CONN/ACEP/BV-01-C<br>GAP/CONN/ACEP/BV-03-C<br>GAP/CONN/ACEP/BV-04-C<br>GAP/CONN/GCEP/BV-01-C<br>GAP/CONN/GCEP/BV-02-C<br>GAP/CONN/GCEP/BV-05-C<br>GAP/CONN/GCEP/BV-06-C<br>GAP/CONN/SCEP/BV-01-C<br>GAP/CONN/SCEP/BV-03-C<br>GAP/CONN/DCEP/BV-01-C<br>GAP/CONN/DCEP/BV-03-C<br>GAP/CONN/DCEP/BV-05-C<br>GAP/CONN/DCEP/BV-06-C<br>GAP/CONN/CPUP/BV-01-C<br>GAP/CONN/CPUP/BV-02-C<br>GAP/CONN/CPUP/BV-03-C<br>GAP/CONN/CPUP/BV-04-C<br>GAP/CONN/CPUP/BV-05-C<br>GAP/CONN/CPUP/BV-06-C<br>GAP/CONN/CPUP/BV-08-C<br>GAP/CONN/CPUP/BV-10-C<br>GAP/CONN/TERM/BV-01-C<br>GAP/CONN/PRDA/BV-01-C<br>GAP/CONN/PRDA/BV-02-C<br>GAP/BOND/NBON/BV-01-C<br>GAP/BOND/NBON/BV-02-C<br>GAP/BOND/NBON/BV-03-C<br>GAP/BOND/BON/BV-01-C<br>GAP/BOND/BON/BV-02-C<br>GAP/BOND/BON/BV-03-C<br>GAP/BOND/BON/BV-04-C<br>GAP/SEC/SEM/BV-21-C<br>GAP/SEC/SEM/BV-37-C<br>GAP/SEC/SEM/BV-38-C<br>GAP/SEC/SEM/BV-22-C<br>GAP/SEC/SEM/BV-39-C<br>GAP/SEC/SEM/BV-40-C<br>GAP/SEC/SEM/BV-23-C<br>GAP/SEC/SEM/BV-24-C<br>GAP/SEC/SEM/BV-56-C<br>GAP/SEC/SEM/BV-57-C<br>GAP/SEC/SEM/BV-58-C<br>GAP/SEC/SEM/BV-59-C<br>GAP/SEC/SEM/BV-60-C<br>GAP/SEC/SEM/BV-61-C<br>GAP/SEC/SEM/BV-26-C<br>GAP/SEC/SEM/BV-41-C<br>GAP/SEC/SEM/BV-42-C<br>GAP/SEC/SEM/BV-27-C<br>GAP/SEC/SEM/BV-43-C<br>GAP/SEC/SEM/BV-44-C<br>GAP/SEC/SEM/BV-28-C<br>GAP/SEC/SEM/BV-29-C<br>GAP/SEC/SEM/BV-62-C<br>GAP/SEC/SEM/BV-63-C<br>GAP/SEC/SEM/BV-64-C<br>GAP/SEC/SEM/BV-65-C<br>GAP/SEC/SEM/BV-66-C<br>GAP/SEC/SEM/BV-67-C<br>GAP/SEC/SEM/BI-09-C<br>GAP/SEC/SEM/BI-10-C<br>GAP/SEC/SEM/BV-45-C<br>GAP/SEC/SEM/BI-20-C<br>GAP/SEC/SEM/BI-21-C<br>GAP/SEC/SEM/BI-22-C<br>GAP/SEC/SEM/BI-23-C<br>GAP/SEC/AUT/BV-11-C<br>GAP/SEC/AUT/BV-12-C<br>GAP/SEC/AUT/BV-13-C<br>GAP/SEC/AUT/BV-14-C<br>GAP/SEC/AUT/BV-17-C<br>GAP/SEC/AUT/BV-18-C<br>GAP/SEC/AUT/BV-19-C<br>GAP/SEC/AUT/BV-20-C<br>GAP/SEC/AUT/BV-21-C<br>GAP/SEC/AUT/BV-22-C<br>GAP/SEC/AUT/BV-23-C<br>GAP/SEC/AUT/BV-24-C<br>GAP/SEC/AUT/BV-25-C<br>GAP/SEC/AUT/BV-27-C<br>GAP/PRIV/CONN/BV-10-C<br>GAP/PRIV/CONN/BV-11-C<br>GAP/PRIV/CONN/BV-12-C<br>GAP/ADV/BV-01-C<br>GAP/ADV/BV-02-C<br>GAP/ADV/BV-03-C<br>GAP/ADV/BV-04-C<br>GAP/ADV/BV-05-C<br>GAP/ADV/BV-08-C<br>GAP/ADV/BV-10-C<br>GAP/ADV/BV-11-C<br>GAP/ADV/BV-14-C<br>GAP/ADV/BV-17-C<br>GAP/ADV/BV-18-C<br>GAP/PADV/PASM/BV-01-C<br>GAP/PADV/PAM/BV-01-C<br>GAP/PADV/PASE/BV-01-C<br>GAP/PADV/PASE/BV-02-C<br>GAP/PADV/PASE/BV-03-C<br>GAP/PADV/PASE/BV-04-C<br>GAP/PADV/PASE/BV-05-C<br>GAP/PADV/PASE/BV-06-C<br>GAP/PADV/PAST/BV-01-C<br>GAP/PADV/PAST/BV-02-C<br>GAP/GAT/BV-04-C<br>GAP/GAT/BV-05-C<br>GAP/GAT/BV-06-C</details>

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
No failed test found.
<details><summary>Successful tests</summary>SM      SM/CEN/EKS/BI-01-C              PASS<br>SM      SM/CEN/EKS/BV-01-C              PASS<br>SM      SM/CEN/JW/BI-01-C               PASS<br>SM      SM/CEN/JW/BI-04-C               PASS<br>SM      SM/CEN/JW/BV-05-C               PASS<br>SM      SM/CEN/KDU/BI-01-C              PASS<br>SM      SM/CEN/KDU/BV-05-C              PASS<br>SM      SM/CEN/KDU/BV-06-C              PASS<br>SM      SM/CEN/KDU/BV-10-C              PASS<br>SM      SM/CEN/OOB/BI-01-C              PASS<br>SM      SM/CEN/OOB/BV-01-C              PASS<br>SM      SM/CEN/OOB/BV-03-C              PASS<br>SM      SM/CEN/OOB/BV-09-C              PASS<br>SM      SM/CEN/PIS/BV-02-C              PASS<br>SM      SM/CEN/PIS/BV-03-C              PASS<br>SM      SM/CEN/PKE/BI-01-C              PASS<br>SM      SM/CEN/PKE/BI-02-C              PASS<br>SM      SM/CEN/PKE/BV-01-C              PASS<br>SM      SM/CEN/PKE/BV-04-C              PASS<br>SM      SM/CEN/PROT/BV-01-C             PASS<br>SM      SM/CEN/SCJW/BI-01-C             PASS<br>SM      SM/CEN/SCJW/BV-01-C             PASS<br>SM      SM/CEN/SCJW/BV-04-C             PASS<br>SM      SM/CEN/SCOB/BI-01-C             PASS<br>SM      SM/CEN/SCOB/BI-04-C             PASS<br>SM      SM/CEN/SCOB/BV-01-C             PASS<br>SM      SM/CEN/SCOB/BV-04-C             PASS<br>SM      SM/CEN/SCPK/BI-01-C             PASS<br>SM      SM/CEN/SCPK/BI-02-C             PASS<br>SM      SM/CEN/SCPK/BV-01-C             PASS<br>SM      SM/CEN/SCPK/BV-04-C             PASS<br>SM      SM/PER/EKS/BI-02-C              PASS<br>SM      SM/PER/EKS/BV-02-C              PASS<br>SM      SM/PER/JW/BI-02-C               PASS<br>SM      SM/PER/JW/BI-03-C               PASS<br>SM      SM/PER/JW/BV-02-C               PASS<br>SM      SM/PER/KDU/BI-01-C              PASS<br>SM      SM/PER/KDU/BV-01-C              PASS<br>SM      SM/PER/KDU/BV-02-C              PASS<br>SM      SM/PER/KDU/BV-07-C              PASS<br>SM      SM/PER/KDU/BV-08-C              PASS<br>SM      SM/PER/OOB/BI-02-C              PASS<br>SM      SM/PER/OOB/BV-02-C              PASS<br>SM      SM/PER/OOB/BV-04-C              PASS<br>SM      SM/PER/OOB/BV-10-C              PASS<br>SM      SM/PER/PIS/BV-01-C              PASS<br>SM      SM/PER/PIS/BV-02-C              PASS<br>SM      SM/PER/PKE/BI-03-C              PASS<br>SM      SM/PER/PKE/BV-02-C              PASS<br>SM      SM/PER/PKE/BV-05-C              PASS<br>SM      SM/PER/PROT/BV-02-C             PASS<br>SM      SM/PER/SCJW/BI-02-C             PASS<br>SM      SM/PER/SCJW/BV-02-C             PASS<br>SM      SM/PER/SCJW/BV-03-C             PASS<br>SM      SM/PER/SCOB/BI-02-C             PASS<br>SM      SM/PER/SCOB/BI-03-C             PASS<br>SM      SM/PER/SCOB/BV-02-C             PASS<br>SM      SM/PER/SCOB/BV-03-C             PASS<br>SM      SM/PER/SCPK/BI-03-C             PASS<br>SM      SM/PER/SCPK/BI-04-C             PASS<br>SM      SM/PER/SCPK/BV-02-C             PASS<br>SM      SM/PER/SCPK/BV-03-C             PASS</details>

**Comment by piotrnarajowski** [comment]
#AutoPTS run mynewt GAP/BROB/BCST/BV-04-C

**Comment by codecoup-tester** [comment]
Scheduled PR https://github.com/apache/mynewt-nimble/pull/1826#issuecomment-2275673088, board: nrf52, estimated start time: 14:15:22, test case count: 1, estimated duration: 0:01:37<details><summary>Test cases to be run</summary>GAP/BROB/BCST/BV-04-C</details>

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
<details><summary>Failed tests</summary>GAP     GAP/BROB/BCST/BV-04-C           FAIL</details>

**Comment by piotrnarajowski** [comment]
#AutoPTS run mynewt SM/CEN/PIS/BV-03-C

**Comment by codecoup-tester** [comment]
Scheduled PR https://github.com/apache/mynewt-nimble/pull/1826#issuecomment-2275928684, board: nrf52, estimated start time: 16:11:14, test case count: 1, estimated duration: 0:02:54<details><summary>Test cases to be run</summary>SM/CEN/PIS/BV-03-C</details>

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
No failed test found.
<details><summary>Successful tests</summary>SM      SM/CEN/PIS/BV-03-C              PASS</details>

**Comment by piotrnarajowski** [comment]
@sjanc please review

**Comment by sjanc** [comment]
last commit should be squashed so that tests always build

**Comment by piotrnarajowski** [comment]
@sjanc done

**Review by sjanc — APPROVED** [review]

**Pull request merged**
