### PR TITLE
porting/nuttx: Fix error: implicit declaration of function 'usleep'

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
Report here:
https://github.com/apache/nuttx/actions/runs/4098214664/jobs/7067171681

### CODE REVIEW

**Review by sjanc — APPROVED** [review]

**Comment by sjanc** [comment]
Hi,

if you could provide a quick instruction on how to setup nuttx env and build samples I could add nuttx port to our Github Actions...

**Comment by xiaoxiang781216** [comment]
> Hi,
> 
> if you could provide a quick instruction on how to setup nuttx env and build samples I could add nuttx port to our Github Actions...

ci includes on:
Docker: https://github.com/apache/nuttx/blob/master/tools/ci/docker/linux/Dockerfile
Script: https://github.com/apache/nuttx/blob/master/tools/ci/cibuild.sh
Testlist: https://github.com/apache/nuttx/tree/master/tools/ci/testlist
Here is the code snippet integrate all pieces:
https://github.com/apache/nuttx/blob/master/.github/workflows/build.yml#L117-L172
For nimble test, you can reduce the testlist to include one test:
sim:nimble

**Comment by sjanc** [comment]
how is nuttx fetching nimble repo? I'd like to test our PRs against nuttx port (like we do for RIOT) and for that I'd have to alter nimble repo in nuttx on-the-fly

**Comment by xiaoxiang781216** [comment]
Here is it: https://github.com/apache/nuttx-apps/blob/master/wireless/bluetooth/nimble/Makefile#L38-L41

**Pull request merged**
