### PR TITLE
apps/bttester: Fix build with EATT enabled

### PR DESCRIPTION
**Pull request by sjanc**
EATT support requires at least same number of COC channels.

### CODE REVIEW

**Comment by sjanc** [comment]
#AutoPTS run mynewt GATT/SR/GAW/BI-32-C

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/apache/mynewt-nimble/pull/1733#issuecomment-2012470485 after 15:39:51.

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
<details><summary>Failed tests</summary>GATT    GATT/SR/GAW/BI-32-C             BTP ERROR</details>

**Comment by sjanc** [comment]
#AutoPTS run mynewt GATT/CL/GAR/BI-07-C GATT/CL/GAR/BV-05-C GATT/SR/GAR/BI-10-C GATT/SR/GAW/BI-05-C

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/apache/mynewt-nimble/pull/1733#issuecomment-2012505703 after 15:52:28.

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
<details><summary>Failed tests</summary>GATT    GATT/SR/GAR/BI-10-C             BTP ERROR<br>GATT    GATT/SR/GAW/BI-05-C             BTP ERROR</details>
<details><summary>Successful tests</summary>GATT    GATT/CL/GAR/BI-07-C             PASS<br>GATT    GATT/CL/GAR/BV-05-C             PASS</details>

**Pull request merged**
