### PR TITLE
nimble/sm: Add support for debug mode

### PR DESCRIPTION
**Pull request by rymanluk**
When MYNEWT_VAL BLE_SM_SC_DEBUG_MODE is set then Secure Manager enters into
Debug Mode. Public and private keys are fix as per Bluetooth 5.1
specification.

Note this is only available for Secure Connections.

### CODE REVIEW

**Comment by andrzej-kaczmarek** [comment]
isn't this the same as `BLE_SM_SC_DEBUG_KEYS`?

**Comment by rymanluk** [comment]
heh, so there is another place with debug keys..did not found it, but maybe we should have one place where debug keys are and not two.

**Comment by andrzej-kaczmarek** [comment]
debug keys enabled with 'BLE_SM_SC_DEBUG_KEYS` are what spec says
the other debug keys have corresponding API to set any keys for debugging purposes

**Comment by rymanluk** [comment]
don't need it as functionality is there already

**Pull request closed without merging**
