### PR TITLE
Support for VS HCI command for reading static random address from controller

### PR DESCRIPTION
**Pull request by sjanc**

### CODE REVIEW

**Comment by vrahane** [comment]
@sjanc The changes look fine to me, not sure why the CI is failing though. Very weird.

**Review by vrahane — APPROVED** [review]

**Comment by utzig** [comment]
> @sjanc The changes look fine to me, not sure why the CI is failing though. Very weird.

```
Error: Unresolved value references:
    BLE_HCI_VS -> 
Setting history (newest -> oldest):
    BLE_HCI_VS: [nimble:MYNEWT_VAL(BLE_CONTROLLER)]
```

**Comment by vrahane** [comment]
@utzig is it because its defined in the same file, it cannot resolve it ?

**Review by vrahane — APPROVED** [review]

**Review by rymanluk — APPROVED** [review]
LGTM

**Pull request merged**
