### PR TITLE
Mesh build fix

### PR DESCRIPTION
**Pull request by sjanc**

### CODE REVIEW

**Review by michal-narajowski — APPROVED** [review]
LGTM

**Comment by KKopyscinski** [comment]
LGTM

**Review by KKopyscinski — APPROVED** [review]

**Comment by KKopyscinski** [comment]
@sjanc I checked it again and CDB is off by default; this fixes issue when CDB is on. Could you change commit title?

**Comment by sjanc** [comment]
Hmm this is what I see in syscfg.yml for mesh:

    BLE_MESH_CDB:
        description: >
            Mesh Configuration Database [EXPERIMENTAL]
        value: 0

**Comment by sjanc** [comment]
with CDB off I get linker error, with CDB on  indeed there is build error.  So none is working without it if settings are enabled

**Comment by KKopyscinski** [comment]
What app is not compiling with CDB off then?

**Pull request merged**
