### PR TITLE
Fix the compiler warning on NuttX

### PR DESCRIPTION
**Pull request by xiaoxiang781216**
Report here: https://github.com/apache/nuttx-apps/actions/runs/4102723052/jobs/7076100328
- Fix ble_hci_socket.c:359:5: warning: implicit declaration of function ‘ble_hci_trans_buf_free’
- Fix SYSINIT_PANIC_ASSERT_MSG refinition warning

### CODE REVIEW

**Comment by xiaoxiang781216** [comment]
@sjanc do you know why the CI fail?

**Comment by sjanc** [comment]
> @sjanc do you know why the CI fail?

looks like some networking issues in github actions, I've restarted failed jobs

**Comment by xiaoxiang781216** [comment]
The patch pass CI now, could you merge it? https://github.com/apache/nuttx-apps/pull/1543 dpends on this patch.

**Comment by sjanc** [comment]
Could you  follow commit conventions? (prefixes, limit commit subject to 72 characters)   eg:
"nimble/transport: Fix compilation warning in socket transport"
"porting: Fix SYSINIT_PANIC_ASSERT_MSG redefinition"


we don't have very strict rules for commit messages but would be good to follow more-or-less what is in history. You can check that with "git log --  PATH_TO_FILE_OR_FOLDER"

**Comment by xiaoxiang781216** [comment]
Done.

**Pull request merged**
