### PR TITLE
Enable NimBLE on Dialog CMAC

### PR DESCRIPTION
**Pull request by andrzej-kaczmarek**
This adds phy, transport and some other changes required to run full NimBLE controller on Dialog CMAC. This means we will now be able to run NimBLE controller on Dialog DA1469x MCU family instead of using binary image with proprietary controller.

### CODE REVIEW

**Comment by sjanc** [comment]
Is tinycrypt copy necessary? We already have it in ext/

**Review by wes3 — APPROVED** [review]
Took a quick look at things and it looks reasonable to me

**Comment by andrzej-kaczmarek** [comment]
> Is tinycrypt copy necessary? We already have it in ext/

for now - yes. I'll dealt with it later.

**Comment by sjanc** [comment]
OK, just add note to LICENSE about TC seconds copy

**Review by sjanc — APPROVED** [review]

**Review by sjanc — APPROVED** [review]

**Comment by benpicco** [comment]
Hi, do you think this could also be used for the DA1458x MCU family or are the differences too big?

**Pull request merged**
