### PR TITLE
nimble/controller: Issue#1135 fix

### PR DESCRIPTION
**Pull request by sada45**
Hi
I found an imperfect point caused by the 32768Hz crystal of nrf and proposed a simple fix. The developer sjanc has confirmed this fix.
The link to this issue: [https://github.com/apache/mynewt-nimble/issues/1135](url)
Happy new year!

### CODE REVIEW

**Comment by sjanc** [comment]
could you put that nice description from issue 1135 in commit message? (not PR, but commit itself) so that it is visible in git history?

**Comment by sjanc** [comment]
also, short code comment why 1 is added would be good too

**Comment by sada45** [comment]
Sorry, it's my first time to PR. So do I need to start a new PR with the right commit message?

**Comment by sjanc** [comment]
No need for new PR.

You can just alter commit message with  'git commit --amend' and then push updated branch (with --force param), PR will be updated automatically

**Comment by sada45** [comment]
Hi sjanc,
Thanks for your time and helpful suggestions! I have correct the commit message and put a comment in the code.

**Pull request closed without merging**
