### PR TITLE
nRF52 PA/LNA support

### PR DESCRIPTION
**Pull request by donaldschen**
Add basic support for radio PA/LNA for nRF52 via PPI.

configure via syscfg defines
- `BLE_PHY_PALNA_PA_ENABLE_PIN`: gpio for enabling the PA for preparing for radio TX.
- `BLE_PHY_PALNA_LNA_ENABLE_PIN`: gpio for enabling the LNA for preparing for radio RX.
- `BLE_PHY_PALNA_PA_ENABLE_PIN_ACTIVE_LOW`: PA enable gpio polarity (1 = active low, 0 = active high)
- `BLE_PHY_PALNA_LNA_ENABLE_PIN_ACTIVE_LOW`: LNA enable gpio polarity (1 = active low, 0 = active high)

### CODE REVIEW

**Comment by andrzej-kaczmarek** [comment]
not sure if this is the final version or just wip (looks like wip), but few comments to start with:
- this needs PR and commit message that explains its purpose and how to use it
- do not add APIs to common `controller` headers unless they are generic and can be implemented for other PHYs
- we do not use nrfx helpers in nrf5x PHY and I would prefer to keep it this way
- check our coding style in existing files and follow it
- I do not quite see where new syscfg are defined

**Comment by donaldschen** [comment]
Hi there, thanks for taking a look at my changes.
- this needs PR and commit message that explains its purpose and how to use it. 
_OK, will update with everything once all the code is firmed up_

- do not add APIs to common controller headers unless they are generic and can be implemented for other PHYs
_See next comment_
- we do not use nrfx helpers in nrf5x PHY and I would prefer to keep it this way
_Sorry I was a little lost when I added this code in, now it makes a more sense to me now. I will move everything into `drivers/nrf52/...` and move all the `ble_phy_palna...` functions into ble_phy.c._

- check our coding style in existing files and follow it
_OK, I'll double check against the coding standard_

- I do not quite see where new syscfg are defined
_I'm not entirely sure where to define the syscfg values since they are board specific. The way I am building this with PA/LNA support is with a custom app with the values defined in `apps/myapp/syscfg.yml`_

**Comment by donaldschen** [comment]
@andrzej-kaczmarek would it be possible for you to review the changes I made? Thanks in advance! Donald

**Comment by sjanc** [comment]
I think PA/LNA support is already in master

**Pull request closed without merging**
