### PR TITLE
apps/bttester: Fix use of extended advertising interface

### PR DESCRIPTION
**Pull request by sjanc**
This shoudl allow to run GAP and GATT tests with BLE_EXT_ADV enabled.

### CODE REVIEW

**Comment by sjanc** [comment]
#AutoPTS run mynewt  GATT/CL/GAR/BI-07-C GATT/CL/GAR/BV-05-C GATT/SR/GAR/BI-10-C GATT/SR/GAW/BI-05-C

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/apache/mynewt-nimble/pull/1735#issuecomment-2014877895 after 12:25:41.

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
No failed test found.
<details><summary>Successful tests</summary>GATT    GATT/CL/GAR/BI-07-C             PASS<br>GATT    GATT/CL/GAR/BV-05-C             PASS<br>GATT    GATT/SR/GAR/BI-10-C             PASS<br>GATT    GATT/SR/GAW/BI-05-C             PASS</details>

**Comment by sjanc** [comment]
#AutoPTS run mynewt GAP

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/apache/mynewt-nimble/pull/1735#issuecomment-2014937349 after 13:06:17.

**Comment by codecoup-tester** [comment]
AutoPTS Bot failed:
Build and flash step failed

**Comment by sjanc** [comment]
#AutoPTS run mynewt GAP/CONN

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/apache/mynewt-nimble/pull/1735#issuecomment-2015248008 after 15:41:09.

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/apache/mynewt-nimble/pull/1735#issuecomment-2015248008 after 15:42:39.

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
<details><summary>Failed tests</summary>GAP     GAP/CONN/DCON/BV-01-C           BTP ERROR</details>
<details><summary>Successful tests</summary>GAP     GAP/CONN/ACEP/BV-01-C           PASS<br>GAP     GAP/CONN/ACEP/BV-03-C           PASS<br>GAP     GAP/CONN/ACEP/BV-04-C           PASS<br>GAP     GAP/CONN/CPUP/BV-01-C           PASS<br>GAP     GAP/CONN/CPUP/BV-02-C           PASS<br>GAP     GAP/CONN/CPUP/BV-03-C           PASS<br>GAP     GAP/CONN/CPUP/BV-04-C           PASS<br>GAP     GAP/CONN/CPUP/BV-05-C           PASS<br>GAP     GAP/CONN/CPUP/BV-06-C           PASS<br>GAP     GAP/CONN/CPUP/BV-08-C           PASS<br>GAP     GAP/CONN/CPUP/BV-10-C           PASS<br>GAP     GAP/CONN/DCEP/BV-01-C           PASS<br>GAP     GAP/CONN/DCEP/BV-03-C           PASS<br>GAP     GAP/CONN/DCEP/BV-05-C           PASS<br>GAP     GAP/CONN/DCEP/BV-06-C           PASS<br>GAP     GAP/CONN/GCEP/BV-01-C           PASS<br>GAP     GAP/CONN/GCEP/BV-02-C           PASS<br>GAP     GAP/CONN/GCEP/BV-05-C           PASS<br>GAP     GAP/CONN/GCEP/BV-06-C           PASS<br>GAP     GAP/CONN/NCON/BV-01-C           PASS<br>GAP     GAP/CONN/NCON/BV-02-C           PASS<br>GAP     GAP/CONN/NCON/BV-03-C           PASS<br>GAP     GAP/CONN/PRDA/BV-01-C           PASS<br>GAP     GAP/CONN/PRDA/BV-02-C           PASS<br>GAP     GAP/CONN/SCEP/BV-01-C           PASS<br>GAP     GAP/CONN/SCEP/BV-03-C           PASS<br>GAP     GAP/CONN/TERM/BV-01-C           PASS<br>GAP     GAP/CONN/UCON/BV-01-C           PASS<br>GAP     GAP/CONN/UCON/BV-02-C           PASS<br>GAP     GAP/CONN/UCON/BV-03-C           PASS<br>GAP     GAP/CONN/UCON/BV-06-C           PASS</details>

**Comment by sjanc** [comment]
#AutoPTS run mynewt GAP/CONN/DCON/BV-01-C

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/apache/mynewt-nimble/pull/1735#issuecomment-2015308754 after 16:12:57.

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
No failed test found.
<details><summary>Successful tests</summary>GAP     GAP/CONN/DCON/BV-01-C           PASS</details>

**Comment by sjanc** [comment]
#AutoPTS run mynewt GAP/ADV

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/apache/mynewt-nimble/pull/1735#issuecomment-2015327011 after 16:20:33.

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
No failed test found.
<details><summary>Successful tests</summary>GAP     GAP/ADV/BV-01-C                 PASS<br>GAP     GAP/ADV/BV-02-C                 PASS<br>GAP     GAP/ADV/BV-03-C                 PASS<br>GAP     GAP/ADV/BV-04-C                 PASS<br>GAP     GAP/ADV/BV-05-C                 PASS<br>GAP     GAP/ADV/BV-08-C                 PASS<br>GAP     GAP/ADV/BV-10-C                 PASS<br>GAP     GAP/ADV/BV-11-C                 PASS<br>GAP     GAP/ADV/BV-14-C                 PASS<br>GAP     GAP/ADV/BV-17-C                 PASS<br>GAP     GAP/ADV/BV-18-C                 PASS</details>

**Comment by sjanc** [comment]
#AutoPTS run mynewt GAP/SEC/AUT/BV-12-C GAP/SEC/AUT/BV-17-C GAP/SEC/AUT/BV-19-C GAP/SEC/SEM/BV-26-C GAP/SEC/SEM/BV-28-C  GAP/SEC/SEM/BV-29-C GAP/SEC/SEM/BV-41-C GAP/SEC/SEM/BV-42-C GAP/SEC/SEM/BV-45-C GAP/SEC/SEM/BV-65-C GAP/SEC/SEM/BV-66-C GAP/SEC/SEM/BV-67-C

**Comment by codecoup-tester** [comment]
Scheduled PR #https://github.com/apache/mynewt-nimble/pull/1735#issuecomment-2015382143 after 16:51:00.

**Comment by codecoup-tester** [comment]
AutoPTS Bot results:
<details><summary>Failed tests</summary>GAP     GAP/SEC/AUT/BV-19-C             INCONC<br>GAP     GAP/SEC/SEM/BV-45-C             BTP ERROR</details>
<details><summary>Successful tests</summary>GAP     GAP/SEC/AUT/BV-12-C             PASS<br>GAP     GAP/SEC/AUT/BV-17-C             PASS<br>GAP     GAP/SEC/SEM/BV-26-C             PASS<br>GAP     GAP/SEC/SEM/BV-28-C             PASS<br>GAP     GAP/SEC/SEM/BV-29-C             PASS<br>GAP     GAP/SEC/SEM/BV-41-C             PASS<br>GAP     GAP/SEC/SEM/BV-42-C             PASS<br>GAP     GAP/SEC/SEM/BV-65-C             PASS<br>GAP     GAP/SEC/SEM/BV-66-C             PASS<br>GAP     GAP/SEC/SEM/BV-67-C             PASS</details>

**Review by andrzej-kaczmarek — APPROVED** [review]

**Pull request merged**
