### PR TITLE
host/ble_att_svr: Reset handles index on attributes reset.

### PR DESCRIPTION
**Pull request by MarceauFillon**
Resets handles index when server's attributes are reset.
Prevents mix-up when attributes are cached.

### CODE REVIEW

**Comment by sjanc** [comment]
you may need to rebase to make CI happy

**Comment by MarceauFillon** [comment]
@sjanc is the target branch wrong?

**Comment by sjanc** [comment]
ahh yes, please make PR against master branch

**Comment by MarceauFillon** [comment]
Done, thanks.

**Comment by andrewleech** [comment]
As some background to this change, we're using nimble as the primary BLE stack in micropython.

During the initial startup of the stack we register the standard gap/gatt services: https://github.com/micropython/micropython/blob/851ecb2da178fff0b60aefdb5af502f28787a7ec/extmod/nimble/modbluetooth_nimble.c#L653

The micropython end user application would later typically define all the desired services/characteristics which is managed dynamically by resetting the registration and building up the required structs to be registered: https://github.com/micropython/micropython/blob/851ecb2da178fff0b60aefdb5af502f28787a7ec/extmod/nimble/modbluetooth_nimble.c#L907

This has been working very well, however we recently discoevered that the handles would continue incrementing over each registration reset, causing difficulties with any paired devices which have cached services/characteristics.

**Review by sjanc — APPROVED** [review]

**Pull request merged**
